### ISSUE TITLE
'find_element_by_name' is it WebDriver issue

### ISSUE THREAD

**Issue by Wabungus43** [hydino2085143/Discord-OTP-Forcer#3]
[WDM] - ====== WebDriver manager ======
2022-07-08 00:48:07,823 INFO ====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
2022-07-08 00:48:07,871 INFO Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
2022-07-08 00:48:07,871 INFO Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - Driver [/home/wabungus123/.wdm/drivers/chromedriver/linux64/103.0.5060.53/chromedriver] found in cache
2022-07-08 00:48:07,997 INFO Driver [/home/wabungus123/.wdm/drivers/chromedriver/linux64/103.0.5060.53/chromedriver] found in cache
/home/wabungus123/Desktop/Discord-OTP-Forcer/src/main.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
Traceback (most recent call last):
  File "/home/wabungus123/Desktop/Discord-OTP-Forcer/src/main.py", line 92, in <module>
    main()
  File "/home/wabungus123/Desktop/Discord-OTP-Forcer/src/main.py", line 35, in main
    loginEmail = driver.find_element_by_name("email")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by hydino2085143** [comment]
Hello! I Don't use linux, so I am not able debug this issue, sorry : ( Please see #1

**Comment by Wabungus43** [comment]
so im trying to this all in windows right? and i get this error

C:\Users\pr0ga\Discord-OTP-Forcer\src\main.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
Traceback (most recent call last):
  File "C:\Users\pr0ga\Discord-OTP-Forcer\src\main.py", line 92, in <module>
    main()
  File "C:\Users\pr0ga\Discord-OTP-Forcer\src\main.py", line 35, in main
    loginEmail = driver.find_element_by_name("email")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

i tried messing with the .env file, making the email and password lines match with the fine element or whatever, that didnt work ended with the same result. any ideas?
